### ISSUE TITLE
[Template] User Story

### ISSUE THREAD

**Issue by kchou94** [RimworldModders/first-aid#3]
#### Pitch
**As a** player 
**I want** to be able to fly a big bad spaceship all over the Rimworld 
**So that** I can finally get rid of those damn raiders and have a raider-meat BBQ afterwards!

#### Acceptance Criteria
- [ ] Able to travel in world map with spaceship
- [ ] Spaceship can attack outposts
- [ ] BBQ

### Tasks
Break the story down into manageable tasks and reference them here.  (Pretend the following are actual tasks...)
- [ ] Allow colonists to caravan in spaceship #1 
- [ ] BBQ pit assets #2
