### ISSUE TITLE
Implement Tier 1 Serum

### ISSUE THREAD

**Issue by kchou94** [RimworldModders/first-aid#8]
#### Pitch
**As a** player 
**I want** to have access to a potent device that can help save lives in the field
**So that** I can save pawns in battle or refugees and turn the tide of a closely matched raid.

**As a** developer 
**I want** this device to be somewhat hard to get your hands on and with some negative aspects
**So that** these don't become easy-to-come-by "freebies" that people spam to win every battle.

#### Acceptance Criteria
- [ ] Craftable serum requires research
- [ ] Serum can be applied in the field
- [ ] Serum applies positive and negative effects
- [ ] Overdose is possible

### Tasks
- [ ] Crafting tier 1 serum
- [ ] T1 serum applies positive effects
- [ ] T1 serum applies negative effects/OD
- [ ] T1 serum texture
